package cz.felk.cvut.erm.conceptual.exception;

/**
 * Superclass of exceptions generated by classes in
 * <code>cz.omnicom.ermodeller.conceptual</code> package.
 */
public abstract class ConceptualException extends Exception {
    /**
     * Message in exception.
     *
     * @return java.lang.String
     */
    public abstract String getMessage();
}
